### ISSUE TITLE
Привет

### ISSUE THREAD

**Issue by Kumigy** [KeeVeeG/vue-numbers-animation#1]
Нашёл твоё резюме, напиши мне на почту kumigy@it-kolibri.com )

**Comment by KeeVeeG** [comment]
Написал)

**Comment by Kumigy** [comment]
Рад видеть.

 

Подскажи поалуйста ты принципиально на фронта ищешь работу или в принципе веб-разработка интересует? 

 

  _____  



С уважением, Руководитель IT-отдела
Перминов Владислав.
Сот.: +7 922 229-22-49
Тел.: +7 (343) 227-47-27 добавочный 21
Сайт:  <http://www.ra-kolibri.com/> www.ra-kolibri.com
